# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('min_percent_grade', models.FloatField(default=0)),
                ('max_percent_grade', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('downloadable', 'downloadable'), ('audit_passing', 'audit_passing'), ('notpassing', 'notpassing'), ('audit_notpassing', 'audit_notpassing')], default=None, max_length=64, null=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('certification', models.ManyToManyField(blank=True, to='control_panel.CertificationIndex')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('earned', models.FloatField(null=True)),
                ('graded', models.FloatField(null=True)),
                ('courses', models.ManyToManyField(to='control_panel.Course')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('min_percent_grade', models.FloatField(default=0)),
                ('max_percent_grade', models.FloatField(default=1.0)),
                ('letter_grade', models.CharField(max_length=255, null=True)),
                ('passed_timestamp', models.DateTimeField(null=True)),
                ('courses', models.ManyToManyField(to='control_panel.Course')),
            ],
        ),
        migrations.AddField(
            model_name='compoundindex',
            name='progress',
            field=models.ManyToManyField(blank=True, to='control_panel.ProgressIndex'),
        ),
        migrations.AddField(
            model_name='compoundindex',
            name='qualification',
            field=models.ManyToManyField(blank=True, to='control_panel.QualificationIndex'),
        ),
        migrations.AddField(
            model_name='certificationindex',
            name='courses',
            field=models.ManyToManyField(to='control_panel.Course'),
        ),
    ]
