# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificationindex',
            options={'verbose_name_plural': 'Certification Indeces'},
        ),
        migrations.AlterModelOptions(
            name='compoundindex',
            options={'verbose_name_plural': 'Compound Indeces'},
        ),
        migrations.AlterModelOptions(
            name='progressindex',
            options={'verbose_name_plural': 'Progress Indeces'},
        ),
        migrations.AlterModelOptions(
            name='qualificationindex',
            options={'verbose_name_plural': 'Qualification Indeces'},
        ),
        migrations.RemoveField(
            model_name='qualificationindex',
            name='passed_timestamp',
        ),
        migrations.AddField(
            model_name='qualificationindex',
            name='max_passed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualificationindex',
            name='min_passed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationindex',
            name='status',
            field=models.CharField(max_length=256, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='qualificationindex',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
