# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_auto_20171029_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressindex',
            name='earned',
        ),
        migrations.RemoveField(
            model_name='progressindex',
            name='graded',
        ),
        migrations.AddField(
            model_name='progressindex',
            name='max_earned',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='progressindex',
            name='max_graded',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='progressindex',
            name='min_earned',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='progressindex',
            name='min_graded',
            field=models.FloatField(default=0),
        ),
    ]
