# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_auto_20171029_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_section',
            field=models.IntegerField(default=1),
        ),
    ]
