# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_course_num_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='es', max_length=16),
        ),
    ]
