# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 22:28
from __future__ import unicode_literals

import control_panel.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0007_auto_20171104_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigngenerator',
            name='name',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigngenerator',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 22, 28, 38, 998036, tzinfo=utc), validators=[control_panel.models.validate_future]),
        ),
    ]
