# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 02:10
from __future__ import unicode_literals

import control_panel.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0008_auto_20171105_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Gesti\xf3n de gobiernos subnacionales para resultados', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigngenerator',
            name='trigger_time',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[control_panel.models.validate_future]),
        ),
    ]
