# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0009_auto_20171106_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mailchimp_list_id',
            field=models.CharField(blank=True, db_column='mailchimp_list_id', max_length=32),
        ),
    ]
