# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0011_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationindex',
            name='email_subject',
            field=models.CharField(default='Test subject', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compoundindex',
            name='email_subject',
            field=models.CharField(default='Test subject', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressindex',
            name='email_subject',
            field=models.CharField(default='Test subject', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualificationindex',
            name='email_subject',
            field=models.CharField(default='Test subject', max_length=256),
            preserve_default=False,
        ),
    ]
