# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0012_auto_20171107_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigngenerator',
            name='trigger_time',
        ),
        migrations.AddField(
            model_name='campaigngenerator',
            name='delay_time',
            field=models.FloatField(default=24),
        ),
        migrations.AddField(
            model_name='campaigngenerator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
