# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0013_auto_20171108_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='click_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='num_emails',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='open_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
