# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0014_auto_20171108_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigngenerator',
            name='delay_time',
        ),
        migrations.AddField(
            model_name='campaigngenerator',
            name='trigger_day',
            field=models.IntegerField(choices=[(0, 'MONDAY'), (1, 'TUESDAY'), (2, 'WEDNESDAY'), (3, 'THURSDAY'), (4, 'FRIDAY'), (5, 'SATURDAY'), (6, 'SUNDAY')], default=1),
        ),
        migrations.AddField(
            model_name='campaigngenerator',
            name='trigger_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 11, 22, 49, 34, 730898, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 11, 22, 49, 58, 11472, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificationindex',
            name='email_subject',
            field=models.CharField(help_text='Merge fields (e.g. *|FNAME|*, *|LNAME|*, *|COURSE|*) are permitted', max_length=256),
        ),
        migrations.AlterField(
            model_name='compoundindex',
            name='email_subject',
            field=models.CharField(help_text='Merge fields (e.g. *|FNAME|*, *|LNAME|*, *|COURSE|*) are permitted', max_length=256),
        ),
        migrations.AlterField(
            model_name='progressindex',
            name='email_subject',
            field=models.CharField(help_text='Merge fields (e.g. *|FNAME|*, *|LNAME|*, *|COURSE|*) are permitted', max_length=256),
        ),
        migrations.AlterField(
            model_name='qualificationindex',
            name='email_subject',
            field=models.CharField(help_text='Merge fields (e.g. *|FNAME|*, *|LNAME|*, *|COURSE|*) are permitted', max_length=256),
        ),
    ]
