# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0015_auto_20171111_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='trigger_time',
            field=models.DateTimeField(help_text='Rounded down automatically to 15-minute multiple'),
        ),
    ]
