# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0016_auto_20171112_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentTypeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email_subject', models.CharField(help_text='Merge fields (e.g. *|FNAME|*, *|LNAME|*, *|COURSE|*) are permitted', max_length=256)),
                ('mode', models.CharField(max_length=256, null=True, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control_panel.Template')),
            ],
            options={
                'verbose_name_plural': 'Enrollment Type Indeces',
            },
        ),
        migrations.AddField(
            model_name='campaigngenerator',
            name='enrollment_index',
            field=models.ManyToManyField(blank=True, to='control_panel.EnrollmentTypeIndex'),
        ),
    ]
