# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0017_auto_20171112_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundindex',
            name='enrollment',
            field=models.ManyToManyField(blank=True, to='control_panel.EnrollmentTypeIndex'),
        ),
    ]
