# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0018_compoundindex_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email_subject', models.CharField(help_text='Merge fields (e.g. *|FNAME|*, *|LNAME|*, *|COURSE|*) are permitted', max_length=256)),
                ('enrolled_only', models.BooleanField(default=False, help_text='Users enrolled with no activity yet')),
                ('participant', models.BooleanField(default=False, help_text='Users with course activity (complement set of enrolled_only')),
                ('min_inactivity_days', models.IntegerField(default=0, help_text='No recorded activity greater than this number of days')),
                ('max_inactivity_days', models.IntegerField(default=100, help_text='No recorded activity less than this number of days')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control_panel.Template')),
            ],
            options={
                'verbose_name_plural': 'Activity Indeces',
            },
        ),
        migrations.AlterField(
            model_name='enrollmenttypeindex',
            name='mode',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='campaigngenerator',
            name='activity_index',
            field=models.ManyToManyField(blank=True, to='control_panel.ActivityIndex'),
        ),
        migrations.AddField(
            model_name='compoundindex',
            name='activity',
            field=models.ManyToManyField(blank=True, to='control_panel.ActivityIndex'),
        ),
    ]
