# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edx', '0002_authuserprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseenrollment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('created', models.DateTimeField(db_index=True, null=True)),
                ('is_active', models.SmallIntegerField()),
                ('mode', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx.AuthUser')),
            ],
            options={
                'db_table': 'student_courseenrollment',
            },
        ),
        migrations.CreateModel(
            name='UserIdMap',
            fields=[
                ('hashid', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edx.AuthUser')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edx.AuthUser', to_field='username')),
            ],
            options={
                'db_table': 'user_id_map',
            },
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='allow_certificate',
            field=models.SmallIntegerField(),
        ),
    ]
