# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edx', '0004_auto_20171025_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesGeneratedcertificate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('download_url', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=5)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('key', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('verify_uuid', models.CharField(max_length=32)),
                ('download_uuid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('error_reason', models.CharField(max_length=512)),
                ('mode', models.CharField(max_length=32)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='edx.AuthUser')),
            ],
            options={
                'db_table': 'certificates_generatedcertificate',
            },
        ),
        migrations.CreateModel(
            name='CoursewareStudentmodule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('module_type', models.CharField(db_index=True, default='problem', max_length=32)),
                ('module_id', models.CharField(db_index=True, max_length=255)),
                ('state', models.TextField(null=True)),
                ('grade', models.FloatField(db_index=True, null=True)),
                ('created', models.DateTimeField(db_index=True)),
                ('modified', models.DateTimeField(db_index=True)),
                ('max_grade', models.FloatField(null=True)),
                ('done', models.CharField(max_length=8)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='edx.AuthUser')),
            ],
            options={
                'db_table': 'courseware_studentmodule',
            },
        ),
        migrations.CreateModel(
            name='GradesPersistentcoursegrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('grading_policy_hash', models.CharField(max_length=255)),
                ('percent_grade', models.FloatField(db_index=True)),
                ('letter_grade', models.CharField(max_length=255)),
                ('passed_timestamp', models.DateTimeField(db_index=True, null=True)),
                ('created', models.DateTimeField(db_index=True)),
                ('modified', models.DateTimeField(db_index=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='edx.AuthUser')),
            ],
            options={
                'db_table': 'grades_persistentcoursegrade',
            },
        ),
        migrations.CreateModel(
            name='GradesPersistentsubsectiongrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('usage_key', models.CharField(db_index=True, max_length=255)),
                ('earned_all', models.FloatField(db_index=True)),
                ('possible_all', models.FloatField(db_index=True)),
                ('earned_graded', models.FloatField(db_index=True)),
                ('possible_graded', models.FloatField(db_index=True)),
                ('first_attempted', models.DateTimeField(db_index=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField(db_index=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='edx.AuthUser')),
            ],
            options={
                'db_table': 'grades_persistentsubsectiongrade',
            },
        ),
        migrations.CreateModel(
            name='StudentAnonymoususerid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anonymous_user_id', models.CharField(max_length=32, unique=True)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='edx.AuthUser')),
            ],
            options={
                'db_table': 'student_anonymoususerid',
            },
        ),
        migrations.CreateModel(
            name='StudentLanguageproficiency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('user_profile_id', models.ForeignKey(db_column='user_profile_id', on_delete=django.db.models.deletion.CASCADE, to='edx.AuthUserprofile')),
            ],
            options={
                'db_table': 'student_languageproficiency',
            },
        ),
    ]
