# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edx', '0005_certificatesgeneratedcertificate_coursewarestudentmodule_gradespersistentcoursegrade_gradespersisten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useridmap',
            old_name='hashid',
            new_name='hash_id',
        ),
    ]
