# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx', '0007_auto_20171027_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursewarestudentmodule',
            name='modified',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
