# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx', '0008_auto_20171027_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatesgeneratedcertificate',
            name='grade',
            field=models.FloatField(),
        ),
    ]
